title:             Shadows
email:             stela.13@hotmail.es
description:       Silent Observation
author:            E
#url:               "localhost:4000"
url:               "http://squarezero.github.io/"
baseurl:

# Social Profiles
#twitter_username:  MsSnot
#github_username:   Estela13
#facebook_username: Estela Bravo

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
